language: python
os: linux

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

python:
  - "3.8"
before_install:
  - pip install --upgrade pip
  - pip install poetry
install:
  - poetry install
script:
  - make style
  - make test
after_success:
  - bash <(curl -s https://codecov.io/bash)
