[tool.poetry]
name = "eddrit"
version = "0.1.2"
description = "Alternative Reddit frontend"
authors = ["corenting <corenting@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
aiofiles = "^0.6.0"
environs = "^9.3.2"
gunicorn = "^20.1.0"
httpx = "^0.18.1"
Jinja2 = "^2.11.3"
lxml = "^4.6.3"
python-multipart="^0.0.5"
starlette = "^0.14.2"
timeago = "^1.0.15"
tldextract = "^3.1.0"
uvicorn = {version = "^0.13.4", extras = ["standard"]}
uvloop = "^0.15.2"

[tool.poetry.dev-dependencies]
black = "^21.5b1"
coverage = {version = "*", extras = ["toml"]}
flake8 = "*"
isort = "*"
mypy = "*"
pdbpp = "*"
pyproject-flake8 = "*"
pytest = "*"
pytest-cov = "*"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.flake8]
max_line_length = 88
extend-ignore = "E501"

[tool.coverage.run]
omit = ["eddrit/config.py"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
