[tool.poetry]
name = "eddrit"
version = "0.4.1"
description = "Alternative Reddit frontend"
authors = ["corenting <corenting@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiofiles = "^0.8.0"
environs = "^9.5.0"
gunicorn = "^20.1.0"
httpx = "^0.23.0"
Jinja2 = "^3.1.2"
lxml = "^4.9.1"
python-multipart = "^0.0.5"
starlette = "^0.20.4"
timeago = "^1.0.16"
tldextract = "^3.3.1"
uvicorn = {version = "^0.18.3", extras = ["standard"]}

[tool.poetry.dev-dependencies]
black = "*"
coverage = {version = "*", extras = ["toml"]}
flake8 = "*"
isort = "*"
mypy = "*"
pdbpp = "*"
pyproject-flake8 = "*"
pytest = "*"
pytest-cov = "*"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true

[tool.flake8]
max_line_length = 88
extend-ignore = "E501"
per-file-ignores = ["__init__.py:F401"]

[tool.coverage.run]
omit = ["eddrit/config.py"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
