[tool.poetry]
name = "eddrit"
version = "0.1.2"
description = "Alternative Reddit frontend"
authors = ["corenting <corenting@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
aiofiles = "^0.7.0"
environs = "^9.3.3"
gunicorn = "^20.1.0"
httpx = "^0.19.0"
Jinja2 = "^3.0.1"
lxml = "^4.6.3"
python-multipart = "^0.0.5"
starlette = "^0.16.0"
timeago = "^1.0.15"
tldextract = "^3.1.2"
uvicorn = {version = "^0.15.0", extras = ["standard"]}
uvloop = "^0.16.0"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
coverage = {version = "*", extras = ["toml"]}
flake8 = "*"
isort = "*"
mypy = "*"
pdbpp = "*"
pyproject-flake8 = "*"
pytest = "*"
pytest-cov = "*"

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
ignore_missing_imports = true
disallow_untyped_defs = true

[tool.flake8]
max_line_length = 88
extend-ignore = "E501"

[tool.coverage.run]
omit = ["eddrit/config.py"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
